### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by inoks** [vaab/colour#18]
Throws Traceback error, than only one color requested
`
list(Color("black").range_to(Color('white'),1))
`
>ZeroDivisionError: float division by zero

Expected list with one element:
`
[<Color black>,]
`

**Comment by vaab** [comment]
It should be fixed. Can you confirm this ?

**Comment by inoks** [comment]
Thanks, now works.

Do you have plan to update version, which are available at https://pypi.python.org/pypi/colour/ ?

**Comment by vaab** [comment]
hmm, I have some other fixes that were waiting on an other branch, I'd like to add them to the next release. How bad is this for you ? I could do a micro-release if this is important to you.

**Comment by inoks** [comment]
Not urgent for me now, i already made fixes in my project for that case.
Thanks for your project!

**Comment by vaab** [comment]
Many thanks for you for taking time to report this bug.

**Comment by vaab** [comment]
I just release colour 0.1.2 with the fix on PyPI. This is a micro-release and it contains only 2 new commits.

**Comment by inoks** [comment]
Thanks!
