### ISSUE TITLE
Implement major color representations

### ISSUE THREAD

**Issue by pradyunsg** [vaab/colour#20]
Nice job with this library.

The only thing I think is that it does not implement all the colour representations. Here's a check-list to motivate you to add those.
- [x] Web (Hex/Colour Names)
- [x] RGB
- [ ] CIELAB (LAB)
- [ ] HCL / LCH
- [x] HSL
- [ ] HSV
- [ ] XYZ
- [ ] CYM
- [ ] CYMK

Possibly the best part of this library is that it is independent (single-file, no dependencies). I request you to please keep it the same.

**Comment by vaab** [comment]
Hehe, thanks for your interest and support, and sharing your POV. There are no plans to get this more complex than it is now. And PR are welcome for all these other formats :), or even some links to page expliciting the conversion algorithms that could be used would surely help these to be released sooner.

**Comment by pradyunsg** [comment]
You could use colorsys. That has RGB, HSV, HSL, YUI.

**Comment by pradyunsg** [comment]
Also, here's a link to a page with the relevant color-conversion formulae. http://www.easyrgb.com/?X=MATH

Looks like colours should be stored as RGB (as `decimal`).

**Comment by pradyunsg** [comment]
Bump. Any chance someone else would work on this?

**Comment by NoAnyLove** [comment]
Cool and nice library, but I'm looking for a library that supports LAB.

**Comment by pradyunsg** [comment]
Closing since doesn't look like anyone's gonna be doing this. :)
