### ISSUE TITLE
Using named tuples

### ISSUE THREAD

**Issue by pradyunsg** [vaab/colour#22]
Currently, All attributes and methods of `Color` return tuples or strings. It should be relatively simple to return namedtuples instead of simple tuples.

Why?
_Namedtuple makes your tuples *_self-document*_. You can easily understand what is going on by having a quick glance at your code._<sup>[1](http://pythontips.com/2015/06/06/why-should-you-use-namedtuple-instead-of-a-tuple/)</sup>

**Comment by pradyunsg** [comment]
Bump.

**Comment by vaab** [comment]
This is an excellent suggestion. Sorry for the late answer, this got lost and stuck between my actual intention to release other stuff containing already this part. Although, if any PR would pop in and that it pass the basic requirements, I'll accept it with pleasure.

Sorry again for this overly late answer anyway.

**Comment by pradyunsg** [comment]
Great. If and when I get the time to do this, I'll shoot a PR.

**Comment by pradyunsg** [comment]
If someone else is interested in doing this, please do.

**Comment by sayeghr** [comment]
Hi @vaab, should this issue be considered closed?

**Comment by pradyunsg** [comment]
Closing since it looks like it got solved.
